import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter, Montserrat } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { NavbarComponent } from '@/components/ui/navbar/navbar'
import { ThemeProvider } from '@/components/theme-provider'
import { Analytics } from "@vercel/analytics/next"

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})
const montserrat = Montserrat({
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn('font-sans', montserrat.className)}
    >
      <body className={`${montserrat.className}  antialiased`}>
        <ThemeProvider
          attribute={'class'}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavbarComponent>{children}</NavbarComponent>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  )
}
